### ISSUE TITLE
最新版本功能失效

### ISSUE THREAD

**Issue by StillMisty** [shatyuka/Zhiliao#123]
![Screenshot_2024-10-23-16-31-08-843_com zhihu andr](https://github.com/user-attachments/assets/2371cfc9-eb43-4462-9429-a436c9193517)

**Comment by shatyuka** [comment]
Fixed in commit bc51ca6.

**Comment by Maozai-Teng** [comment]
> Fixed in commit [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3).修复于提交 bc51ca6 。

这个修复后的插件去哪里下载呀_(:3」 ∠）_

**Comment by StillMisty** [comment]
> > Fixed in commit [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3).修复于提交 [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3) 。
> 
> 这个修复后的插件去哪里下载呀_(:3」 ∠）_

项目 Actions 里

**Comment by Maozai-Teng** [comment]
> > > Fixed in commit [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3).修复于提交 [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3) 。
> > 
> > 
> > 这个修复后的插件去哪里下载呀_(:3」 ∠）_
> 
> 项目 Actions 里

好的，谢谢你！

**Comment by Maozai-Teng** [comment]
> > Fixed in commit [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3).修复于提交 [bc51ca6](https://github.com/shatyuka/Zhiliao/commit/bc51ca605cb3166b69990867acea39f1c71e34c3) 。
> 
> 这个修复后的插件去哪里下载呀_(:3」 ∠）_

test
