### ISSUE TITLE
知了小bug反馈

### ISSUE THREAD

**Issue by LinnyR** [shatyuka/Zhiliao#13]
机型:红米k30pro
系统:MIUI12.5 21.4.8
知了版本:21.04.03
出现的问题:
1.开启显示卡片类别的选项卡之后，刚进入知乎时候是显示是正常的
![Screenshot_2021-04-12-14-47-53-732_com zhihu android](https://user-images.githubusercontent.com/38827394/114352136-20260f00-9b31-11eb-91cb-0d9a537410e6.jpg)
然后切换到我的，点击付费咨询
![IMG_20210412_144608](https://user-images.githubusercontent.com/38827394/114352029-fc62c900-9b30-11eb-84de-1f31e37c9330.jpg)
进入后，这个页面标圈的地方好像有些异常
![IMG_20210412_144947](https://user-images.githubusercontent.com/38827394/114352492-87dc5a00-9b31-11eb-8db4-6c482cba288d.jpg)
2.然后返回到主页面，刷新页面变成了这样子，标记的标题和问题标题之间的距离变得非常大。
![Screenshot_2021-04-12-14-39-42-345_com zhihu android](https://user-images.githubusercontent.com/38827394/114352584-a80c1900-9b31-11eb-9fe9-b40bdd7b60a8.jpg)

**Comment by LinnyR** [comment]
知乎版本7.8

**Comment by shatyuka** [comment]
均无法复现。第一个问题关闭知了再测试。
![](https://user-images.githubusercontent.com/31368738/114354179-73837600-9ba0-11eb-82fc-c728cc39e233.png)

**Comment by LinnyR** [comment]
> 均无法复现。第一个问题关闭知了再测试。

你好,第一个问题关闭知了后还是出现.应该是miui12.5系统或者软件本身的问题.
第二个问题还是出现了,很奇怪的bug.hhh~
已经打赏,感谢作者的付出~~

**Comment by LinnyR** [comment]
而且点别的功能返回后刷新都不会出现第二个问题这种情况,只有打开了值乎返回才会复现emmm

**Comment by LinnyR** [comment]
而且点别的功能返回后刷新都不会出现第二个问题这种情况,只有打开了付费咨询返回才会复现emmm
