### ISSUE TITLE
[小bug] 左右划灵敏度

### ISSUE THREAD

**Issue by YYoungC** [shatyuka/Zhiliao#16]
三星s21，安卓11，lsp最新版，知了最新版，知乎play版最新版

重启知乎，上次设置好的灵敏度就会变回默认（不知道是不是默认，我也忘了默认是多少了，反正我每次设置成8，爽到飞起，但重启后就变得很不敏感）

**Comment by shatyuka** [comment]
Fixed in commit 1e81da6.
