### ISSUE TITLE
建议增加左右滑动等待超时机制

### ISSUE THREAD

**Issue by Proanx** [shatyuka/Zhiliao#18]
有不少回答是内夹代码块的，很多时候需要横向移动来翻阅，很容易导致左右翻页的误触发。
然后有个阴间办法是左右滑动以后按住不动就不会翻页，但是松手就翻页了。不知道能不能加个超时机制当滑动变成长按时取消触发左右滑动

**Comment by shatyuka** [comment]
Added in 1c60e0f.
