### ISSUE TITLE
请问安装后不显示图标是什么原因？

### ISSUE THREAD

**Issue by samz1288** [shatyuka/Zhiliao#19]
机型:华为p30
系统:EMUI10
知了版本:21.06.04
出现的问题: 安装以后桌面无图表显示，知乎设置内也无相关内容。

**Comment by shatyuka** [comment]
设计如此

**Comment by samz1288** [comment]
那请问该如何设置软件呢

**Comment by samz1288** [comment]
知乎上看不到设置，用的太极阴，模块勾选、重启已经都试过了，还是不显示，还请大大指点

**Comment by samz1288** [comment]
知乎版本是6.14

**Comment by lolisix** [comment]
你用 快捷方式打开 看看, 里面应该有知了的活动吧?
