### ISSUE TITLE
知乎热更新导致模块失效

### ISSUE THREAD

**Issue by shatyuka** [shatyuka/Zhiliao#2]

**Comment by VeroFess** [comment]
目前我自己发现的解决方法

下载Lucky Patcher并安装 -> 选择 "知乎" -> 更改应用组件 -> 更改权限和活动项 -> 拖到最下面， 把所有 com.tencent.tinker 开头的都禁用(即点成红色) -> 点击"重建应用"，之后去系统设置中 **完全清除所有数据**，再次使用就不会被热更骚扰了

**Comment by VeroFess** [comment]
啊吧， 是我输了， 方案2.0 

ADB Shell 上去之后，拿到root权限， 把/data/data/com.zhihu.android/tinker目录里的文件全都删了，然后给这个目录设置一个你喜欢的权限，理论上可以根治

**Comment by shatyuka** [comment]
> 啊吧， 是我输了， 方案2.0 
> 
> ADB Shell 上去之后，拿到root权限， 把/data/data/com.zhihu.android/tinker目录里的文件全都删了，然后给这个目录设置一个你喜欢的权限，理论上可以根治

@VeroFess 我是想保留热更新，拿到tinker的classloader进行hook

**Comment by shatyuka** [comment]
Fixed in commit 46ec30c.
