### ISSUE TITLE
Zhiliao settings button missing

### ISSUE THREAD

**Issue by wmm-xs** [shatyuka/Zhiliao#22]
I can find settings button on zhihu setting  menu, but about 2 seconds later, that's missing, and I need reload application, and fast click setting,

and sometimes ad remove can't working on blog

Device: oppo r9st
Zhiliao version: 21.06.04
Xposed installer: 3.5.1
Zhihu version:7.14.0(5222) install from Google store

**Comment by wmm-xs** [comment]
Zhiliao maybe have some error, how can I find the log file

**Comment by wmm-xs** [comment]
Xposed log is empty

**Comment by wmm-xs** [comment]
Another phone
Google pixel 4XL
Android 11
I can't find zhiliao settings button

**Comment by shatyuka** [comment]
https://github.com/shatyuka/Zhiliao/wiki

**Comment by shatyuka** [comment]
Q1: Fixed in 895fca2.
Q2: won't fix
