### ISSUE TITLE
[功能建议]可否去除关注tab页的小红点？

### ISSUE THREAD

**Issue by finlaywang** [shatyuka/Zhiliao#31]
关注的人都取关了，每次打开还是会有小红点。如图所示，可否在菜单“去除小红点”里加上这块谢谢！
![Screenshot_2021-08-07-15-51-46-590_com zhihu android](https://user-images.githubusercontent.com/20654507/128593104-dee6414a-b27b-4989-a888-0618a8fa2b0f.jpg)

**Comment by shatyuka** [comment]
Fixed in c73dd00.
