### ISSUE TITLE
可否增加一个功能,使得每次打开知乎,知了都会自动帮几个问题邀请人来回答.

### ISSUE THREAD

**Issue by lolisix** [shatyuka/Zhiliao#33]
我本人在学习时会提出许多问题,  提出问题后就需要邀请人来回答, 但是知乎有每日邀请上限.
为了充分利用每日邀请次数, 所以我想可否在我每次打开知乎时, 知了自动帮忙在我提前设定好的问题下面, 根据问题标签来随机的邀请我指定的人数, 这样每天浪费的次数就不会太多, 可以有更多的人看到我的提问.
这种功能可能实现吗?

**Comment by shatyuka** [comment]
不会
