### ISSUE TITLE
自定义过滤上似乎有些问题

### ISSUE THREAD

**Issue by cmmdwl** [shatyuka/Zhiliao#4]
例如我在内容过滤上过滤了 先上领取入口 
但是信息流推送依旧会出现这些东西

**Comment by cmmdwl** [comment]
![Screenshot_2021-01-25-15-00-29-824_com.zhihu.android.jpg](https://user-images.githubusercontent.com/21263352/105671717-22a79e00-5f1e-11eb-811e-c404fdf99679.jpg)![Screenshot_2021-01-25-15-00-21-380_com.zhihu.android.jpg](https://user-images.githubusercontent.com/21263352/105671724-2509f800-5f1e-11eb-81f7-b184e6a0599d.jpg)
![Screenshot_2021-01-25-15-01-37-956_com.zhihu.android.jpg](https://user-images.githubusercontent.com/21263352/105671777-3c48e580-5f1e-11eb-9f3f-8f1eb2d0764f.jpg)

**Comment by shatyuka** [comment]
https://github.com/shatyuka/Zhiliao/wiki#faq
https://www.runoob.com/regexp/regexp-tutorial.html

**Comment by cmmdwl** [comment]
![Screenshot_2021-01-28-09-51-37-044_com.zhihu.android.jpg](https://user-images.githubusercontent.com/21263352/106078494-7d274100-614e-11eb-85db-fef7fc368935.jpg)![Screenshot_2021-01-28-09-51-44-280_com.zhihu.android.jpg](https://user-images.githubusercontent.com/21263352/106078499-7e586e00-614e-11eb-8141-86b2f99fd28d.jpg)
很抱歉，根据全文匹配方式填写的正则式依旧会出现推送

**Comment by lolisix** [comment]
把每个子表达式之间用或 | 来链接
