### ISSUE TITLE
[功能建议]去除标题为问句的文章。

### ISSUE THREAD

**Issue by lolisix** [shatyuka/Zhiliao#40]
经过我观察，知乎上绝大多数“题目的最后一位字符为问号"?"(问号有全角的，也有半角的)”的文章都是推广软文，可以屏蔽掉这一类文章吗？
<a href="https://sm.ms/image/oGt8nTs4Q7qUJrW" target="_blank"><img src="https://s2.loli.net/2022/01/01/oGt8nTs4Q7qUJrW.jpg" ></a>

**Comment by shatyuka** [comment]
动动脑子

**Comment by lolisix** [comment]
> 动动脑子

大佬给点提示呀，难道说只靠正则表达式就可以判断文章与问题吗？
