### ISSUE TITLE
[功能建议]去除提问下方的”圈子“选项。

### ISSUE THREAD

**Issue by lolisix** [shatyuka/Zhiliao#41]
部分问题下面都有“圈子”这个没意义的东西，可以屏蔽掉吗？
ps：为什么我说这东西没用？因为我提问一个泛函分析的问题，下面的圈子竟然是追星相关！牛头不对马嘴呀。
<a href="https://sm.ms/image/MytXs4fF1xlEZmr" target="_blank"><img src="https://s2.loli.net/2022/01/01/MytXs4fF1xlEZmr.jpg" ></a>

**Comment by shatyuka** [comment]
你自己选的tag
