### ISSUE TITLE
隐藏“我的”会员卡片后布局异常

### ISSUE THREAD

**Issue by actforjason** [shatyuka/Zhiliao#43]
有一片空白，刷新时高度还会变

![Screenshot_20220117_185024_com.zhihu.android.png](https://user-images.githubusercontent.com/57058325/149756473-bd795c35-e8f9-41e5-a454-34920d510fa1.png)

**Comment by actforjason** [comment]
另外，下边 书架 到 直播 这块能去掉吗？几乎没啥用

**Comment by Mubai-meng** [comment]
降级，别用高版本

**Comment by shatyuka** [comment]
Fixed in commit 6b6accb.
