### ISSUE TITLE
无法上下滑动切换回答

### ISSUE THREAD

**Issue by Fe3O4-Git** [shatyuka/Zhiliao#6]
即使关闭“左右划”功能也是这样，悬浮按钮也始终不显示

**Comment by shatyuka** [comment]
Fixed in 45b4dcf4ff6490a7ad671bb2396be3ae9c8a06db

**Comment by Fe3O4-Git** [comment]
@shatyuka 左右切换回答功能仍然是不可用的

**Comment by shatyuka** [comment]
> @shatyuka 左右切换回答功能仍然是不可用的

我也没有说修复了
