### ISSUE TITLE
[功能建议] 去除盲水印

### ISSUE THREAD

**Issue by andylizi** [shatyuka/Zhiliao#71]
![](https://user-images.githubusercontent.com/12008103/188303714-b8ff034a-0dcd-4b6c-8224-dd04fd896121.png)![](https://user-images.githubusercontent.com/12008103/188303717-a7a56835-ee8c-416a-ae17-f046783811fb.png)

本质就是 `rgb(254, 254, 254)` 的文字。第一行是用户 ID，可以反查用户名。第二行是 UNIX 时间戳。

网上有一些现成的工具可以提取水印，例如：https://stegonline.iculture.cc/

**Comment by shatyuka** [comment]
commit 1d52f9d, 0a28a1f.
