### ISSUE TITLE
功能建议：自动删除知乎生成的LOG

### ISSUE THREAD

**Issue by hxh19950701** [shatyuka/Zhiliao#74]
知乎运行一直在后台生成大量LOG，然而却从不删除，导致占用越来越大。
据我分析，以下文件夹均为知乎LOG：
/data/data/com.zhihu.android/files/（日期字符串，如2022-10-14）
/data/data/com.zhihu.android/files/app_log
/data/data/com.zhihu.android/files/crash
/data/data/com.zhihu.android/files/log
/data/data/com.zhihu.android/files/logback
/data/data/com.zhihu.android/files/picture_log
/data/data/com.zhihu.android/files/upload_log
/data/data/com.zhihu.android/files/vediter_log
/data/data/com.zhihu.android/files/video_log
每次启动知乎都删掉上面的文件夹，就实现自动删除了。希望作者能实现，谢谢！

**Comment by shatyuka** [comment]
commit c322a11.

**Comment by shatyuka** [comment]
日志会自动备份到日期目录，我觉得保留下当天的日志比较好
