### ISSUE TITLE
[功能建议]屏蔽回答底部的"相关搜索"

### ISSUE THREAD

**Issue by DeltaFlyerW** [shatyuka/Zhiliao#84]
![image](https://user-images.githubusercontent.com/48078918/224196798-336e29ad-d93f-4c43-8f4b-d413126b100d.png)
昨天刚推送的新变更,目前仅在少数回答下出现,由于安装的是旧版本知乎,推测在webview层

**Comment by DeltaFlyerW** [comment]
var handler = function (event) {
    var comment = document.querySelector("section[class~='AnswerPage-AnswerCommentSection']")
    if (!comment && event) {
        comment = event.target.querySelector("section[class~='AnswerPage-AnswerCommentSection']")
        console.log(event.target)
    }
    if (comment) {
        var parent = comment.parentElement
        console.log(parent, comment)
        var removedChildren = []
        for (var child of parent.children) {
            if (!child.className.includes("AnswerPage-AnswerCommentSection")) {
                removedChildren.push(child)
            }
        }
        removedChildren.forEach(it => {
            parent.removeChild(it)
        })
        document.removeEventListener("DOMNodeInserted", handler)
    }
}
document.addEventListener("DOMNodeInserted", handler)
handler()

**Comment by shatyuka** [comment]
commit afaacda.
