### ISSUE TITLE
［Bug］ClassNotFoundException: com.tencent.tinker.loader.app.TinkerApplication

### ISSUE THREAD

**Issue by RyanLoil** [shatyuka/Zhiliao#86]
系统信息
MIUI 13 开发版
Xposed为LSPosed

LSPosed
API 版本：93
Xposed API 调用保护：未启用
Dex 优化器包装：支持
框架版本：1.8.6 (6712)
管理器版本：1.8.6 (6712)
系统版本：12 (API 31)
设备：Xiaomi 2109119BC 
系统架构：arm64-v8a

Bug效果
知了无法运行，优化失败（知乎设置界面没有知了栏）

报错信息
![Screenshot_2023-03-25-15-31-33-047_org lsposed manager](https://user-images.githubusercontent.com/50242494/227704107-aa7d8003-dfc0-4f31-9015-eb9d32f2ef19.jpg)

如需其他信息，供之不胜荣幸。

**Comment by shatyuka** [comment]
commit 6efdb72.
