### ISSUE TITLE
【BUG反馈】去关键字搜索 功能开启后回答无法正常加载

### ISSUE THREAD

**Issue by aoguai** [shatyuka/Zhiliao#88]
**描述错误**
“去关键字搜索” 功能开启后回答无法正常加载
关闭 “去关键字搜索” 功能后答案恢复正常显示

**截图**
![846608F6FB47DF9F32E862AADC44761E](https://user-images.githubusercontent.com/34203474/227773885-f865cd60-032c-4109-ad01-c05e63d1777f.jpg)

**系统信息**
 - 知了版本 23.03.25
 - 知乎版本 7.5.0(4112)

**Comment by yyzx2016lht** [comment]
8.75.0也遇到了，部分问答有这种情况，不是全部都有

**Comment by shatyuka** [comment]
commit 28f6440.
