### ISSUE TITLE
xposed tool植入后打开就闪退

### ISSUE THREAD

**Issue by ArkhalisDragon** [shatyuka/Zhiliao#93]
rt，知乎安装包从豌豆荚下载，版本从8.23到8.59不等，嵌入3.25日release的知了后可以正常安装但是一打开就闪退。

**Comment by Mubai-meng** [comment]
用Lspatch把，貌似打包原理不一样，无解

**Comment by ArkhalisDragon** [comment]
> 用Lspatch把，貌似打包原理不一样，无解

是的，我昨晚改用lspatch打包就能用了
